DROP TASK LOAD_CURATED_SALES;
DROP STREAM ADIDAS_SALES_STG_STREAM;
DROP PIPE ADIDAS_SALES_PIPE;
DROP STAGE ADIDAS_SALES_STAGE;
DROP TABLE ADIDAS_SALES_STG;
DROP TABLE ADIDAS_SALES_CURATED;
DROP DATABASE SNOWPIPE_AUTO_INGEST;
