CREATE OR REPLACE TABLE ADIDAS_SALES_CURATED (
    RETAILER VARCHAR(2000),
    RETAILER_ID NUMBER,
    INVOICE_DATE VARCHAR(2000),
    REGION VARCHAR(2000),
    STATE VARCHAR(2000),
    CITY VARCHAR(2000),
    PRODUCT VARCHAR(2000),
    FINAL_PRICE NUMBER
);
