CREATE OR REPLACE PIPE ADIDAS_SALES_PIPE
AUTO_INGEST=TRUE
AS
COPY INTO ADIDAS_SALES_STG
FROM @ADIDAS_SALES_STAGE
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR='CONTINUE';

-- check pipe 

DESC PIPE ADIDAS_SALES_PIPE;
SHOW PIPES LIKE 'ADIDAS_SALES_PIPE';
