CREATE OR REPLACE TASK LOAD_CURATED_SALES
SCHEDULE='1 MINUTE'
AS 
INSERT INTO ADIDAS_SALES_CURATED
SELECT 
    RETAILER,
    RETAILER_ID,
    INVOICE_DATE,
    REGION,
    STATE,
    CITY,
    PRODUCT,
    PRICE_PER_UNIT+10 AS FINAL_PRICE
FROM ADIDAS_SALES_STG_STREAM;

ALTER TASK LOAD_CURATED_SALES RESUME;
